server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
mybatis:
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  type-aliases-package: com.bokecc.boot.dto
#  configuration:
##  延迟加载
#    lazy-loading-enabled: true
##    按要求延迟加载,如果为true,则会按层延迟加载
#    aggressive-lazy-loading: false
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_test?useSSL=false&&characterEncoding=utf8
    username: root
    password: 123456
#logging:
#  level:
#    org.springframework:WARN
#    com.bokecc.boot.mapper:DEBUG
#  file: logs/spring-boot-logging.log




